/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-mdb.h
 #	source generated by 4D Plugin Wizard
 #	Project : mdb
 #	author : miyako
 #	2024/05/14
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MDB_H
#define PLUGIN_MDB_H

#include "4DPluginAPI.h"
#include "mdbsql.h"
#include "mdbtools.h"
#include <stdlib.h>

#include "C_TEXT.h"
#include "4DPlugin-JSON.h"

#pragma mark -

static void mdb_sql(PA_PluginParameters params);

#endif /* PLUGIN_MDB_H */
